# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.5

# Site settings
title:              Bikoo's world 
logo:               # Logo image URL
description:        Say, Dream, Enjoy, Me
baseurl:            'https://bik00.github.io' # The subpath of your site, e.g. /blog
url:                'https://bik00.github.io' # The base hostname & protocol for your site
twitter:            https://twitter.com/aspirethemes
facebook:           https://www.facebook.com/aspirethemes
instagram:          https://www.instagram.com/aspirethemes

markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:     Bonil Koo
    bio:      행복은 내안에 존재한다고 믿는 초보 개발자. 인생의 이야기를 만들어 나가는 Creator as Devloper. 
    gravatar: # 블로그 프로필 사진? 링그를 건다.
    email:    bikoo3002@naver.com
    website:  https://bik00.github.io
    github:   https://github.com/Bik00
    twitter:  # 트위터 주소
